### ISSUE TITLE
Cant pass in release branches in git2consul

### ISSUE THREAD

**Issue by vigneshsenapathy** [Cimpress-MCP/git2consul#108]
Hi,

I am trying to pass in release branches to git2consul like release/test but it keeps on pulling the old branch called develop even though the git2consul.json is updated. Below is my git2consul.json

{
  "version": "1.0",
  "repos" : [{
    "name" : "sample_configuration",
    "url" : "https://github.com/ryanbreen/git2consul_data.git",
    "branches" : ["release/test"],
    "hooks": [{
      "type" : "polling",
      "interval" : "1"
    }]
  }]
}

**Comment by calvn** [comment]
There is no branch called "release/test" on "https://github.com/ryanbreen/git2consul_data.git". Can you poll "dev" instead as your test?

**Comment by vigneshsenapathy** [comment]
@calvn  i just gave an example of the github and release branch. 
I had earlier deployed develop, and then when i deployed release/test it didnt pick it up

**Comment by vigneshsenapathy** [comment]
@calvn : so is there a way to pass in release branches to git2consul. As currently i am seeing the way i am passing is actually not working

**Comment by calvn** [comment]
Can you try to clear the cache directory so that it re-syncs with the new branch?

**Comment by vigneshsenapathy** [comment]
@calvn  :  tried deleting the cache directory. it still picked up the develop branch.

**Comment by vigneshsenapathy** [comment]
@calvn : i think i had the same issue with other branches but i think i figured out what the issue was. So i added command to /etc/init.d folder. So it keeps on runnings. So i did a reload and it started picking up the new branch. I will try it with release branch to make sure it works and let you know.

thanks,
