### ISSUE TITLE
Omit repo name from prefix?

### ISSUE THREAD

**Issue by eyalzek** [Cimpress-MCP/git2consul#112]
Is there a way to achieve this behavior with the current version? I don't know if it's useful for most people, but it's definitely needed in my case.

**Comment by eyalzek** [comment]
Created a PR for that if anyone is interested in this functionality.

https://github.com/Cimpress-MCP/git2consul/pull/113

**Comment by bitsofinfo** [comment]
+1

**Comment by bitsofinfo** [comment]
Could be confusing to have both? https://github.com/Cimpress-MCP/git2consul/pull/100
