### ISSUE TITLE
Add documentation to describe how to run/deploy this?

### ISSUE THREAD

**Issue by petemounce** [Cimpress-MCP/git2consul#20]
Hi there

We're looking at using this; it sounds like exactly how we'd want to manage configuration information.

Could you please enhance the docs to describe how to run it, though? Sorry if I've missed something obvious - not so familiar with node.

I'm assuming something like
* set up a repo to hold configuration
* put a configuration file into `KV:/git2consul/config` (per https://github.com/Cimpress-MCP/git2consul#configuration)
* ... run something!

**Comment by ryanbreen** [comment]
Good point. We could definitely use a Getting Started guide. I'll work on that today.

**Comment by ryanbreen** [comment]
How does this look?  https://github.com/Cimpress-MCP/git2consul#quick-start-guide

**Comment by ryanbreen** [comment]
Closing for now.  Feel free to reopen if you think it needs more.

**Comment by petemounce** [comment]
I think you're missing a key after the branches value...? Sorry, no real
computer to check right now.

--

**Comment by ryanbreen** [comment]
Do you mean in this section:
```
/sample_configuration/dev/sample.conf
/sample_configuration/dev/sample.json
/sample_configuration/dev/sample.yaml
```
The name of this configuration is `sample_configuration`.  The branch is `dev`.  And the file names from the git repo are our keys.  So I think this section is accurate, but let me know if the error you saw was elsewhere.
