### ISSUE TITLE
Loading config properties as keys

### ISSUE THREAD

**Issue by benschw** [Cimpress-MCP/git2consul#22]
Support for the option to parse the source config files from the watched git repo and recreate the structure of the config's properties as a tree of kv pairs in consul

**Comment by ryanbreen** [comment]
Interesting.  Could you provide a little more detail about what you're looking for, potentially with some examples?  That'll make it easier to make sure we're on the same page.

**Comment by benschw** [comment]
the idea is, that given the config file:

`sample.json`

    {
        "foo": {
            "bar": "baz"
        }
    }


which would normally be loaded to facilitate the following interface with consul's http api:

    GET /namespace/sample.json
    {
        "foo": {
            "bar": "baz"
        }
    }

if the option to "load properties" or whatever was set, would instead facilitate the following interface with consul'd http api:

    GET /namespace/sample.json/foo/bar
    baz

**Comment by ryanbreen** [comment]
Ahh, interesting. Let me give that some thought. Seems like a reasonable ask.

**Comment by ryanbreen** [comment]
I'm thinking a git repo is either configured to be in this mode or is not in this mode.  I can't think of a clean way to support this expansion conditionally.  I guess you could have some pattern matching thing in the repo config, but it seems easier to just namespace these in their own subtree.

Thoughts?

**Comment by benschw** [comment]
I like it: a repo is configured one way or the other.

pattern matching could be a future feature if it turns out it would be useful (one way to do this would be to configure the same repo twice with different namespaces and a different "include-pattern")

**Comment by benschw** [comment]
e.g.

    "repos" : [{
      "name" : "github_data_keys",
      "url" : "git@github.com:ryanbreen/git2consul_data.git",
      "mode" : "keys",
      "include": "keys/*"
    },{
      "name" : "github_data_content",
      "url" : "git@github.com:ryanbreen/git2consul_data.git",
      "mode" : "content",
      "include": "config/*"
    }]

**Comment by ryanbreen** [comment]
Yep, something like that. Cool.

**Comment by ryanbreen** [comment]
I decided to leave .json in the key name.  I kinda like that because it makes it very obvious what's going on, especially since I also decided to support non-JSON files in repos that support `expand_keys`.

**Comment by ryanbreen** [comment]
Published as version 0.9.0.

**Comment by benschw** [comment]
Awesome! Thanks!
