### ISSUE TITLE
Does git2consul update ALL of the files/keys in a repo?

### ISSUE THREAD

**Issue by darron** [Cimpress-MCP/git2consul#24]
Or just the changed ones?

Our Consul cluster goes into leadership election/transition almost every git2consul push - just trying to narrow down potential sources of the problem.

**Comment by darron** [comment]
I should also note:

1. If we push code to a KV space that's not being watched - there's no leadership transitions at all.
2. It's just when we push code to a KV space that's being watched - then the leadership transition happens pretty much 100% of the time.

**Comment by ryanbreen** [comment]
git2consul will only update the KVs that changed.  It goes through the git diff and finds all added, deleted, or modified files and takes the appropriate action with the corresponding KVs.

If you push code to the KV space being watched via an HTTP call or other non-git2consul mechanism, do you see the same behavior?

**Comment by darron** [comment]
Thanks @ryanbreen - that's what I had thought - but thought I would ask.
