### ISSUE TITLE
Entrypoint option in config_seeder.js

### ISSUE THREAD

**Issue by cmfatih** [Cimpress-MCP/git2consul#28]
@ryanbreen : How we can use `--entrypoint` (`-e`) for `config_seeder.js`? I found https://github.com/Cimpress-MCP/git2consul/blob/master/utils/config_seeder.js#L29 So looks like it is not possible atm. 

My problem is that I'm running `git2consul` in a container with `BRIDGE` mode and Consul service is on different host instead 127.0.0.1. So I wish there is something `node utils/config_seeder.js /tmp/git2consul.json --entrypoint 10.0.2.15` OR `CONSUL_URL=10.0.2.15:8500 node utils/config_seeder.js /tmp/git2consul.json`

**Comment by ryanbreen** [comment]
Yeah, I didn't consider the Docker use case when first designing git2consul.  I can definitely see how that would cause a problem.  I'll give this some thought, but I'm also happy to take patches.

**Comment by cmfatih** [comment]
I can implement `ENV` solution without making breaking changes. So basically we can set `global.endpoint` to `GIT2CONSUL_ENDPOINT` if `--entrypoint` is not provided.

Otherwise ( adding `--entrypoint` into `config_seeder.js` ) I can't see a solution without making breaking changes.

**Comment by satar** [comment]
Hello, I have a similar problem in that I want to load files located on a separate server into Consul server. I tried to simply update global.endpoint in lib/index.js to point to the ip of the consul server. However, I get the following when I attempt to run it:

Config value is not valid JSON: undefined

I will admit, not savvy with javascript but it seems this would have worked.

**Comment by satar** [comment]
I could also really use this solution. I need to be able to override consul server IP. I am not savvy with npm nor javascript for that matter. I know that I have been able to make this work by manually updating the following two hardcoded references to localhost:

in lib/index.js:
global.endpoint = "127.0.0.1";

in node_modules/consul/lib/consul.js:
opts.host || '127.0.0.1'

I would like to be able to specify this thru either a parameter or an environment variable. I am sure this is probably pretty easy to do but at a loss for how to do it. I would have thought passing --host when running the node would work but it did not.

**Comment by ryanbreen** [comment]
This is available in 0.12.0 and up.
