### ISSUE TITLE
Add ability to synchronise specific folder

### ISSUE THREAD

**Issue by harnash** [Cimpress-MCP/git2consul#29]
Hello.

I would love to see option to allow synchronising a given subfolder (path) of the repo. The problem is that we have multiple data centres with specific configuration for each. With current solution requires me to store configuration on different branches (one branch per DT) or store configuration in a subfolders (on folder per DT).

I we had option to allow synchronise specific repo we could divide our configuration like this:
```
/datacentre1
/datacentre2
....
```
and then in config (on a specific datacentre):
```json
{
     "repos": [
         {
             "source_folder": "/datacentre1"
         },
     ]
}
```

**Comment by ryanbreen** [comment]
Yep, that seems like a reasonable request.

**Comment by ryanbreen** [comment]
Take a look.  I believe GH-30 implements this in a satisfactory fashion.

**Comment by harnash** [comment]
Thank you! I will test it ASAP.
