### ISSUE TITLE
Support variable git2consul config locations

### ISSUE THREAD

**Issue by ryanbreen** [Cimpress-MCP/git2consul#45]
We should allow users to select the KV in which git2consul config is stored.

**Comment by momania** [comment]
And maybe make the default `service/git2consul`, like Hasicorp's own tools like [Consul Replicate](https://github.com/hashicorp/consul-replicate) does too.

**Comment by ryanbreen** [comment]
This is released in 0.12.1.

**Comment by ryanbreen** [comment]
I opted to leave the config key in the same location by default for backwards compat.
