### ISSUE TITLE
Polling seems to stop randomly

### ISSUE THREAD

**Issue by split3** [Cimpress-MCP/git2consul#55]
I have git2consul running inside of a docker container and I'm trying to dig into an issues in which it appears that the polling seems to stop.  When I look at the container logs some last actions I see many times is that is detected a change and sync'd the KV store and then there is no more polling after that.

I'm currently using 0.12.1

Is there anything in particular that might cause this behavior?  Would intermittent issues of connectivity with the git repository cause any failures and for it to stop working?

**Comment by split3** [comment]
I have 3 different environments that point to 3 different Consul clusters and they all seemed to stop working at close to the same time.

Qa:
```
{"name":"git2consul","hostname":"6b501f9a3a9b","pid":1,"level":10,"msg":"Handling record external/prod/services/service-1 of type A","time":"2016-03-04T20:34:09.329Z","v":0}
```
Perf:
```
{"name":"git2consul","hostname":"1f2bbff0696e","pid":1,"level":10,"msg":"Handling record external/prod/services/service-1 of type A","time":"2016-03-04T20:33:55.269Z","v":0}
```

Stage:
```
{"name":"git2consul","hostname":"d73b86456616","pid":1,"level":10,"msg":"Handling record external/prod/services/service-1 of type A","time":"2016-03-04T20:33:59.073Z","v":0}
{"name":"git2consul","hostname":"d73b86456616","pid":1,"level":50,"msg":"config poll failure due to Error: consul: kv.get: read ECONNRESET.  Ignoring...","time":"2016-03-04T20:36:28.226Z","v":0}
```

Here is a sample of my configuration as well:
```
{
  "version": "1.0",
  "logger" : {
    "name" : "git2consul",
    "streams" : [{
      "level": "trace",
      "stream": "process.stdout"
    }]
  },
  "repos" : [
    {
      "name" : "api-gateway-external",
      "url" : "ommitted",
      "include_branch_name": false,
      "source_root": "external/perf",
      "mountpoint": "service/us",
      "branches" : ["master"],
      "hooks": [{
        "type" : "polling",
        "interval" : "1"
      }]
    }
  ]
}
```
Note that the source_root is different for each environment: external/perf, external/qa, and external/stage.  So in those logs, all of those environments are responding to a change that is outside the source_root even (external/prod) and then that is the last message except for stage which reported some connectivity issue with the KV store.

**Comment by ryanbreen** [comment]
Can you test again with 0.12.3?  I believe you're seeing the behavior reported and fixed here: GH-47.

**Comment by split3** [comment]
Sure, let I'll update our containers and see if that fixes the issue and let you know.

**Comment by split3** [comment]
So far it appears to still be polling as desired.  I will keep monitoring for a few days and let you know, but so far so good.

**Comment by ryanbreen** [comment]
Ok, cool.  I'm going to close this, then, but feel free to reopen if polling breaks.
