### ISSUE TITLE
Allow for Branches to be determined from ENV vars

### ISSUE THREAD

**Issue by stephenlawrence** [Cimpress-MCP/git2consul#76]
As a user, I would like to be able to set and ENV var called something like BRANCHES that would allow me to dynamically set to config branches setting when I run git2consul in certain environments where I only want a single branch to be injected into the Consul cluster.

**Comment by cleung2010** [comment]
I believe this can be done by having a different version of your configuration file for git2consul that gets deployed to your machine based on what is your target environment. Tools like Puppet, Chef, etc. can achieve this trivially. 

Optionally, you can manipulate the config file dynamically with these tools. If you use Puppet, for example, the env-to-branch mapping can be dynamically set to the configuration file via templates and Puppet variables as documented [here](https://docs.puppet.com/puppet/4.4/reference/lang_template.html).

I don't think setting target branches with env variables is the proper approach here.

**Comment by stephenlawrence** [comment]
The use-case for this is for a twelve-factor app dockerized git2consul container. When we build the container we copy in our default config.json that is hardcoded to poll our "dev" branch. So when this container gets deployed to a QA environment we would need a way to "override" the branches config value so that an ENV variable could be set when we start the container and git2consul would use as the branches value from ENV instead of the config branches setting.

**Comment by cleung2010** [comment]
Closing this. For further explanation see #79.
