### ISSUE TITLE
unable to test on my consul server 

### ISSUE THREAD

**Issue by SMR39** [Cimpress-MCP/git2consul#88]
Hi guys ,

I am currently testing git2consul and would like to implement at our company .  I am finding issues to load example config to our K/V store at consul . 

I am following the readme provided . Is there something aim doing wrong ? 

`git2consul --config-file /tmp/git2consul.json`

```{"name":"git2consul","hostname":"consul-20032495","pid":25691,"level":30,"msg":"Adding /tmp/git2consul.json to KV git2consul/config as: \n{\n  \"version\": \"1.0\",\n  \"repos\" : [{\n    \"name\" : \"sample_configuration\",\n    \"url\" : \"https://github.com/ryanbreen/git2consul_data.git\",\n    \"branches\" : [\"dev\"],\n    \"hooks\": [{\n      \"type\" : \"polling\",\n      \"interval\" : \"1\"\n    }]\n  }]\n}\n","time":"2016-08-06T01:41:34.225Z","v":0}```

```{"name":"git2consul","hostname":"consul-20032495","pid":25691,"level":50,"err":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect ECONNREFUSED\n    at errnoException (net.js:901:11)\n    at Object.afterConnect [as oncomplete] (net.js:892:19)","code":"ECONNREFUSED"},"msg":"connect ECONNREFUSED","time":"2016-08-06T01:41:34.233Z","v":0}```

p.s Our consul cluster is https endpoint.

same result with `git2consul --endpoint consul.example.com --port 80 --config-file /tmp/git2consul.json`

**Comment by cleung2010** [comment]
You might have to provide`--endpoint` and `--port` flags if you are querying the non-default Consul HTTP API.

**Comment by SMR39** [comment]
@cleung2010  thanks for the reply . I have the same Issue even if i provided --endpoint and --port

**Comment by SMR39** [comment]
i was using wrong port 👍  thanks for your help it is now running yay !

**Comment by cleung2010** [comment]
Awesome! I was just about to reply, but glad you got it resolved.
