### ISSUE TITLE
[Enhancement] Optional Flag for <branch>.ref File

### ISSUE THREAD

**Issue by NRay7882** [Cimpress-MCP/git2consul#94]
Our team has a requirement to duplicate the contents of a repo into Consul to be read by another process. This other process has a strict dependency on the Consul structure. Additionally, we run git2consul on-demand rather than having it running as a polling process. Here's what our command looks like:

`git2consul --endpoint <CONSUL_URL> --port 8500 --config-file <JSON CONFIG> -n --config_key <CONSUL_KEY_PATH>`

After using git2consul to push our keys up, an additional file is found in the root of the path where the keys are located. This file is named 'develop.ref', after the branch we're using from our git repo. The contents of the file have the SHA-1 from our latest commit on that branch that we're pushing. Looking through the documentation I could not find a mention of this file.

Is it possible that a flag can be added to make the creation of this file optional, or if git2consul is dependent on this key, can the flag be configured to remove this key as a last step? I've uploaded a screenshot for our environment to show the file in question. Thanks.

![git2consul_github_question](https://cloud.githubusercontent.com/assets/6548792/17711396/78083e36-63bf-11e6-8a99-dfa18dee6aa8.png)

**Comment by calvn** [comment]
The creation of this .ref file is internal to, and needed in, git2consul. In order for git2consul to work, it needs to know about the state of the contents for that particular path in order to perform diffs and changes. Instead of using a database or some other external state storage system, we decided to use git itself in order for git2consul to figure out changes and update KVs accordingly. Without this, git2consul would have to rewrite all KVs from that path down every time it detected a change, which is less than ideal.

**Comment by NRay7882** [comment]
Thanks for the quick reply!

I figured that was the case, because our use-case is for pushing the contents of the repo on top of whatever is already in Consul, we don't have much dependence for tracking these changes outside of the repo. I'm having our job post a "curl -X DELETE" command since the path is static, I'm going to use this configuration going forward unless there's a better recommended approach for removing this file. Thanks again.

**Comment by calvn** [comment]
@NRay7882 No problem! I think the behavior on git2consul would be to rewrite the KVs for that entire branch when it would detect a change, but I might be wrong on this one. I am going to close this, but feel free to re-open if there are any related issues that arise with your approach.
